jobs:
 test:
  runs-on: ubuntu-latest
  strategy:
   matrix:
    node:
  steps:
   - uses: action/checkout@v4
   - uses: action/setup-node@v4
   with:
    node-version: ${[ matrix.node ]}
   - run: node --version
  
